# Utiliza una imagen base ligera de Node.js
FROM node:16-alpine
# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app
# Copia los archivos package.json y package-lock.json al directorio de trabajo
COPY package*.json ./
# Instala las dependencias de la aplicación
RUN npm install
# Copia todos los archivos del proyecto al directorio de trabajo
COPY . .
# Construye la aplicación
RUN npm run build
# Expone el puerto 3000 para la aplicación
EXPOSE 3000
# Comando por defecto para iniciar la aplicación
CMD ["npm", "start"]
